/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemaGestion;

import com.sun.awt.AWTUtilities;
import java.awt.Image;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author sevilla
 */
public class JFLogin extends javax.swing.JFrame {

    /**
     * Creates new form JFLogin
     */
    public JFLogin() {
        initComponents();
        this.setLocationRelativeTo(null);
        //adaptacion de una imagen
        setIconImage(new ImageIcon(getClass().getResource("../media/iconoBar.png")).getImage());
        ImageIcon logo= new ImageIcon(getClass().getResource("../media/logo-juegos.png"));
        Icon icono= new ImageIcon(logo.getImage().getScaledInstance(lblLogo.getWidth(), lblLogo.getHeight(),Image.SCALE_DEFAULT));
        lblLogo.setIcon(icono);
        this.repaint();
        //fin de la adaptacion
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Ingreso = new javax.swing.JPanel();
        jlUsuario = new javax.swing.JLabel();
        jlContra = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        image = new javax.swing.JLabel();
        IniciarSesion = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        msmusuario = new javax.swing.JLabel();
        msmpassword = new javax.swing.JLabel();
        msmlogin = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jlUser = new javax.swing.JLabel();
        jbISesion = new javax.swing.JButton();
        txtUser = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        lblLogo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Ingreso.setBackground(new java.awt.Color(250, 250, 250));
        Ingreso.setPreferredSize(new java.awt.Dimension(290, 580));
        Ingreso.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlUsuario.setFont(new java.awt.Font("Lemonade Stand", 0, 14)); // NOI18N
        jlUsuario.setText("Usuario");
        Ingreso.add(jlUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        jlContra.setFont(new java.awt.Font("Lemonade Stand", 0, 14)); // NOI18N
        jlContra.setText("Contrasena");
        Ingreso.add(jlContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        jSeparator3.setBackground(new java.awt.Color(0, 102, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 153, 102));
        Ingreso.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 190, 10));
        Ingreso.add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        IniciarSesion.setBorder(null);
        IniciarSesion.setBorderPainted(false);
        IniciarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IniciarSesionMouseClicked(evt);
            }
        });
        IniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarSesionActionPerformed(evt);
            }
        });
        Ingreso.add(IniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, -1));
        Ingreso.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, -1, -1));

        msmusuario.setBackground(new java.awt.Color(255, 255, 255));
        msmusuario.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        msmusuario.setForeground(new java.awt.Color(206, 87, 69));
        Ingreso.add(msmusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 190, 20));

        msmpassword.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        msmpassword.setForeground(new java.awt.Color(206, 87, 69));
        Ingreso.add(msmpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 190, 20));

        msmlogin.setFont(new java.awt.Font("Segoe UI Semilight", 0, 10)); // NOI18N
        msmlogin.setForeground(new java.awt.Color(201, 7, 13));
        msmlogin.setText("...");
        Ingreso.add(msmlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 10, -1));

        jSeparator4.setBackground(new java.awt.Color(0, 102, 0));
        jSeparator4.setForeground(new java.awt.Color(0, 153, 102));
        Ingreso.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 190, 10));

        jlUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/icons8-user_filled.png"))); // NOI18N
        Ingreso.add(jlUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, -1));

        jbISesion.setBackground(new java.awt.Color(188, 204, 189));
        jbISesion.setText("Iniciar Sesion");
        jbISesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbISesionMouseClicked(evt);
            }
        });
        Ingreso.add(jbISesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, -1, -1));

        txtUser.setBackground(new java.awt.Color(250, 250, 250));
        txtUser.setBorder(null);
        txtUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUserKeyTyped(evt);
            }
        });
        Ingreso.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 190, -1));

        txtPassword.setBackground(new java.awt.Color(250, 250, 250));
        txtPassword.setBorder(null);
        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPasswordKeyTyped(evt);
            }
        });
        Ingreso.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 190, -1));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/logo-juegos.png"))); // NOI18N
        Ingreso.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 470, 150, 40));

        getContentPane().add(Ingreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 35, -1, 520));

        jPanel1.setBackground(new java.awt.Color(0, 102, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(243, 243, 243));
        jLabel4.setText("Login");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

  
        
    private void IniciarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IniciarSesionMouseClicked

    }//GEN-LAST:event_IniciarSesionMouseClicked

    private void IniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IniciarSesionActionPerformed

    private void txtUserKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserKeyTyped
        switch (CValidaciones.numerosYletrasMsm(evt,txtUser)) {
            case 1:
                msmusuario.setText("");
                break;
            case 2:
                msmusuario.setText("Caracter no valido");
                break;
            case 3:
                msmusuario.setText("Solo se permiten 10 caracteres");
                break;
            default:
                break;
        }
    }//GEN-LAST:event_txtUserKeyTyped

    private void txtPasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyTyped
        //Validaciones.soloNumerosyLetras(evt,password);
        if(CValidaciones.numerosYletrasMsm(evt,txtPassword)==1){
            msmpassword.setText("");
        }else if(CValidaciones.numerosYletrasMsm(evt,txtPassword)==2){
            msmpassword.setText("Caracter no valido");
        }else if(CValidaciones.numerosYletrasMsm(evt,txtPassword)==3){
            msmpassword.setText("Solo se permiten 10 caracteres");
        }
    }//GEN-LAST:event_txtPasswordKeyTyped

    private void jbISesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbISesionMouseClicked
        logi();  
    }//GEN-LAST:event_jbISesionMouseClicked

    private void logi(){
       String usu=txtUser.getText();
       String pas=new String(txtPassword.getPassword());
       Consultas kl=new Consultas();
       int a = kl.acceder(usu,pas);
       if (a==1){
           JFMenuRoot menuR= new JFMenuRoot();  
           this.setVisible(false);
           menuR.setVisible(true);
       }else if(a==2){
           JFMenuEmpleado menuE= new JFMenuEmpleado();
           this.setVisible(false);
           menuE.setVisible(true);
       }else{
          msmlogin.setText("Datos incorrectos");
       }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Ingreso;
    private javax.swing.JButton IniciarSesion;
    private javax.swing.JLabel image;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JButton jbISesion;
    private javax.swing.JLabel jlContra;
    private javax.swing.JLabel jlUser;
    private javax.swing.JLabel jlUsuario;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel msmlogin;
    private javax.swing.JLabel msmpassword;
    private javax.swing.JLabel msmusuario;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
    CConexion cc=new CConexion();
    Connection cn=cc.conexion();
}
