/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemaGestion;

import com.sun.awt.AWTUtilities;
import java.awt.Color;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.Timer;
import javax.swing.border.LineBorder;
import javax.swing.border.LineBorder;
import sun.util.logging.PlatformLogger;
/**
 *
 * @author sevilla
 */
public class Loader extends javax.swing.JFrame {

    /**
     * Creates new form Loader
     */
    public Loader() {
        initComponents();
        this.setLocationRelativeTo(null);
        AWTUtilities.setWindowOpaque(this, false);
        setIconImage(new ImageIcon(getClass().getResource("../media/iconoBar.png")).getImage());
        //adaptacion de una imagen
        ImageIcon logo= new ImageIcon(getClass().getResource("../media/logo-juegos.png"));
        Icon icono= new ImageIcon(logo.getImage().getScaledInstance(lblLogo.getWidth(), lblLogo.getHeight(),Image.SCALE_DEFAULT));
        lblLogo.setIcon(icono);
        this.repaint();
        //fin de la adaptacion
        setForeground(new Color(15,119,62));
    }

    public Timer timer;
    public JFrame loader=this;
    
    public class Progreso implements ActionListener{
        public void actionPerformed(ActionEvent evt){
            //setBorder(new LineBorder(new Color(R,G,B)));
            //setForeground(new Color(R,G,B));
            int n=barraProgresos.getValue();
            if(n<100){
                n++;
                barraProgresos.setValue(n);
                lblTiempos.setText(Integer.toString(n)+"%");
            }else{
                try{
                    Thread.sleep(1000);
                }catch(InterruptedException ex){
                    Logger.getLogger(Loader.class.getName()).log(Level.SEVERE,null,ex);
                }
                timer.stop();
                JFLogin l = new JFLogin();
                l.setVisible(true);
                loader.setVisible(false);
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        barraProgresos = new javax.swing.JProgressBar();
        lblTiempos = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        barraProgresos.setForeground(new java.awt.Color(51, 204, 0));
        jPanel1.add(barraProgresos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 560, 20));

        lblTiempos.setText("....");
        jPanel1.add(lblTiempos, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, -1, -1));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/logo-juegos.png"))); // NOI18N
        jPanel1.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 575, 172));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        timer = new Timer(50,new Progreso());
        timer.start();
        setForeground(new Color(15,119,62));
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Loader().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barraProgresos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblTiempos;
    // End of variables declaration//GEN-END:variables
}
